# -*- coding: utf-8 -*-
__version__ = '0.1.0'
"""
/***************************************************************************
 smart_map
                                 A QGIS plugin
 Interpolation using Kriging and Machine Learning and generate Management Zones for a set of soil samples
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-08-15
        copyright            : (C) 2018 by Gustavo Willam Pereira (IFSUDESTE-MG)/Domingos Sárvio Magalhães Valente (UFV)/Daniel Marçal de Queiroz (UFV)/Andre Luiz de Freitas Coelho (UFV)/Sandro Manuel Carmelino Hurtado (UFU)
        email                : gustavowillam@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import os
import sys

# Put the local extlibs/ folder (provisioned third-party deps such as
# scikit-learn) on sys.path BEFORE importing the plugin, so its module-level
# `import sklearn` resolves. numpy/pandas/scipy come from QGIS and are not
# shadowed; skfuzzy/pysal/krig are vendored in-tree.
_plugin_dir = os.path.dirname(__file__)
_extlibs_path = os.path.join(_plugin_dir, 'extlibs')
if os.path.isdir(_extlibs_path) and _extlibs_path not in sys.path:
    sys.path.insert(0, _extlibs_path)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load smart_map class from file smart_map.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Provision (or re-provision after a QGIS Python upgrade) the deps matching
    # the running interpreter before importing the plugin.
    from . import extlibs_manager
    if extlibs_manager.needs_provision():
        extlibs_manager.provision()
    extlibs_manager.ensure_on_path()

    from .Smart_Map import smart_map
    return smart_map(iface)
