# -*- coding: utf-8 -*-
"""
/***************************************************************************
 smart_map
                                 A QGIS plugin
 Interpolation using Kriging and Machine Learning and generate Management Zones for a set of soil samples
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-08-15
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Gustavo Willam Pereira (IFSUDESTE-MG)/Domingos Sárvio Magalhães Valente (UFV)/
		                                   Daniel Marçal de Queiroz (UFV)/Andre Luiz de Freitas Coelho (UFV)/
                                           Sandro Manuel Carmelino Hurtado (UFU)
        email                : gustavowillam@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtCore, QtWidgets, QtGui 
from qgis.PyQt.QtCore import QTranslator, QCoreApplication, QVariant #, QSettings, qVersion
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QTableWidgetItem, QProgressDialog
from qgis.PyQt.QtGui import QIcon, QPixmap, QColor, QBrush 

from qgis.core import QgsProject             #get the directory for project QGIS
from qgis.core import QgsSettings            #read QGIS locale for language auto-detection  
from qgis.core import QgsProcessingFeedback  #generate LayerRaster Clipped 
from qgis.core import QgsVectorFileWriter    #Convert  .shp em .csv   ou  .csv  em .shp 
from qgis.core import QgsVectorLayer         #Create  VetorLayer   (.shp)
from qgis.core import QgsCoordinateReferenceSystem, QgsFields, QgsPointXY, QgsGeometry, QgsField, QgsWkbTypes, QgsFeature
from qgis.core import QgsMapLayerProxyModel, QgsMapLayerType, QgsLayerTreeLayer, QgsRasterLayer #Register VectorLayer no Qgis 
from qgis.core import QgsColorRampShader, QgsSingleBandPseudoColorRenderer, QgsRasterBandStats, QgsRasterShader, QgsStyle

import qgis.utils                            #check qgis version  

import processing
from processing.core.Processing import Processing
Processing.initialize()

from qgis.utils import plugins


#Initialize Qt resources from file resources.py
from . import resources

#import resources 
#from .resources import *


#Import the code for the dialog (new pure PyQt views)
from .views.main_dialog import SmartMapDialog
from .Smart_Map_About  import smart_mapAbout

#Import controllers
from .controllers.data_ctrl import DataController
from .controllers.grid_ctrl import GridController
from .controllers.variogram_ctrl import VariogramController
from .controllers.kriging_ctrl import KrigingController
from .controllers.svm_ctrl import SVMController
from .controllers.zones_ctrl import ZonesController
from .controllers.ui_ctrl import UIController

from .managers.interpolation_manager import InterpolationManager
from .managers.spatial_analysis_manager import SpatialAnalysisManager
from .managers.zones_manager import ZonesManager
from .managers.data_manager import DataManager


import os, os.path
from os.path import expanduser
import re
import time             
import subprocess          
import math 
import platform

system = platform.system()  #[Windows, Linux, Darwin]

if system != 'Darwin':  #PIL do not is install in MacOS  
    from PIL import Image  


import matplotlib.path as mplPath 
import matplotlib.pyplot as plt1  #plot map of points Limite Area 
import matplotlib.pyplot as plt2  #plot the semivariogram 
import matplotlib.pyplot as plt3  #plot Map Interpolated (OK / SVM)
#import matplotlib.pyplot as plt4  #plot Map Interpolated (OK-SD)
import matplotlib.pyplot as plt5  #plot Grafic of Cross Validation (OK / SVM)
import matplotlib.pyplot as plt6  #plot Grafic of Number Ideal of Class - Performance Fuzzy Index (FPI), Normalised Classification Entropy (NCE)
import matplotlib.pyplot as plt7  #plot Management Zones

from scipy import spatial                                  #to calculate IDW com cKDTree.query, KDTree.query_ball_point


#import the code for the Utilities 
from .utils import install_deps                            #Install deps on QGIS: sklearn, skfuzzy, pysal 

import numpy as np
import pandas as pd 
#import sklearn 

from .utils import functions                               #Utility functions -> file functions.py 





#file semivariogram.py  (new version, with use of class) -> to generate semivariogram (Model, Range, Sill, Nugget)  
from .krig import semivariogram                                                 

#arquivo kriging.py     (new version, with use of class) -> to generate Kriging DAGAPy 
from .krig import kriging 


from sklearn import svm                                    #Import the model to use Support Vector Machine

from sklearn.model_selection import train_test_split       #Using Skicit-learn to split data into training and testing sets

from sklearn.preprocessing import scale                    #to normalize the data of different attributes to generate Management Zones  

from sklearn.preprocessing import StandardScaler           #to normalize the data of different attributes to generate ML with SVM   

#import skfuzzy as fuzz                                    #to define management zones using fuzzy-K-means
from .skfuzzy.cluster import _cmeans



'''
raster_value('Estatisticas_GO_OK_OK_Grid_Predictions_K_38_6d530038_b366_4829_8c4d_5cc9d87aff10', 1, make_point($x, $y))
pandas, scikit-learn, scikit-fuzzy, pysal, scikit-optimize, pyKrige do not work in the QGIS plugin.   
have to install from the OSGEO4W-shell as an administrator
In cmd of OSGEO4W- shell go to folder C:\Program Files\QGIS 3.10\apps\python37\

type 
  
python -m pip install pandas          // to install pandas    1.0.3        #qgis3
python -m pip install scikit-learn    // to install sklearn   0.22.2       #qgis3  //dependence of scipy 1.4.1 
python -m pip install scikit-fuzzy    // to install scikit-fuzzy 0.4.2.    #to generate management zones using fuzzy-k-means, from interpolated maps
python -m pip install pysal==2.0      // to calculate Index of Moran       #pysal 2.2  error during installation


if you install pip in the OSGEO4W-shell, the installation of libraries can be done via pip command
  
type: pip install pandas               // to install pandas        
type: pip install scikit-learn         // to install scikit-learn    
type: pip install scikit-fuzzy         // to install scikit-fuzzy 
type: pip install pysal==2.0           // to install pysal -> Calculate Índex of Moran 
'''



# Handle high resolution displays:
if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
   QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
   
if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
   QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)




class smart_map:
    """QGIS Plugin Implementation."""

    
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgisInterface
        """


        #Save reference to the QGIS interface
        self.iface = iface

        #initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        
        '''
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir,  'i18n',  'smart_map_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)
        '''

        # Language is auto-detected from the QGIS locale (no manual switch).
        # Source strings are Portuguese; English is the default and is shown by
        # loading the pt->en translation unless QGIS is set to Portuguese.
        self._install_translator()

        # Get path absolute
        self.path_absolute = QgsProject.instance().readPath("./")

        # Icon path (will be set in initGui)
        self.icon_path = ':/plugins/Smart_Map/icon.png'

        # Create the dialog (after translation) and keep reference
        self.dlg = SmartMapDialog(self.iface, self.plugin_dir, self.icon_path, self.tr)

        # Initialize controllers
        self.data_ctrl = None
        self.grid_ctrl = None
        self.variogram_ctrl = None
        self.kriging_ctrl = None

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Smart-Map')

        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'Smart-Map')
        self.toolbar.setObjectName(u'Smart-Map')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in run() to survive plugin reloads
        self.first_start = True
        self.Index_LayerAtual  = -1         #Index_LayerCurrent starts with a negative value -> was not defined at the beginning of the program


    def _install_translator(self):
        """Auto-detect the UI language from the QGIS locale (default English).

        Source strings are Portuguese. English is the default: the pt->en
        translation is installed unless QGIS is set to Portuguese, in which case
        the source (Portuguese) strings are shown as-is. No manual language switch.
        """
        locale = QgsSettings().value('locale/userLocale', 'en_US')
        self.language = 'Portuguese' if str(locale).lower().startswith('pt') else 'English'

        if self.language == 'English':
            locale_path = os.path.join(self.plugin_dir, 'i18n', 'smart_map_pt_to_en.qm')
            if os.path.exists(locale_path):
                self.translator = QTranslator()
                self.translator.load(locale_path)
                QCoreApplication.installTranslator(self.translator)


    def closeEvent(self, event):


        close = QMessageBox.question(self.dlg, self.tr('Mensagem'), self.tr('Deseja realmente sair?'), QMessageBox.Yes | QMessageBox.No)

        if close == QMessageBox.Yes:

            try:
                # mMapLayerComboBox lives on the data view in the new architecture.
                self.dlg.get_data_view().mMapLayerComboBox.currentIndexChanged.disconnect()
            except (TypeError, AttributeError):
                pass  # Ignore if no connections exist / view not built yet

            event.accept()

        else:
            event.ignore()
       
        
    #noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """

        #to generate file .ts using GUI 
        #C:\ProgramData\Anaconda3\Library\bin>pylupdate5 Smart_Map_dialog.ui -ts Smart_Map_dialog.ts

        #to generate file  .qm using file .ts 
        #C:\ProgramData\Anaconda3\Library\bin>lrelease smart_map_pt_to_en.ts            


        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("smart_mapDialogBase", message)



    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        self.icon_path = ':/plugins/Smart_Map/icon.png'
        
        self.add_action(
            self.icon_path,
            text=self.tr(u'Smart-Map'),
            callback=self.run,
            parent=self.iface.mainWindow())
      

    def unload(self):
        
        
        #if 'sklearn' in sys.modules:
        #    del sys.modules["sklearn"]
		
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Smart-Map'), action)
            self.iface.removeToolBarIcon(action)

        # remove the toolbar
        del self.toolbar

    def _initialize_controllers(self):
        """Initialize and wire controllers to views."""
        data_view = self.dlg.get_data_view()
        variogram_view = self.dlg.get_variogram_view()
        kriging_view = self.dlg.get_kriging_view()
        svm_view = self.dlg.get_svm_view()
        zones_view = self.dlg.get_zones_view()

        # Create managers
        self.interp_mgr = InterpolationManager()
        self.spatial_mgr = SpatialAnalysisManager()
        self.zones_mgr = ZonesManager()
        self.data_mgr = DataManager()

        # Data controller
        self.data_ctrl = DataController(
            data_view, self.iface, self.plugin_dir, self.path_absolute,
            self.icon_path, self.language, self.tr
        )

        # Grid controller
        self.grid_ctrl = GridController(
            data_view, self.data_ctrl, self.icon_path, self.path_absolute, self.tr
        )
        # Boundary state is owned by grid_ctrl; give data_ctrl a back-reference so it
        # can read df_limite / Contorno_Definido from the single owner (grid_ctrl).
        self.data_ctrl.grid_ctrl = self.grid_ctrl

        # Variogram controller
        self.variogram_ctrl = VariogramController(
            variogram_view, self.data_ctrl, self.interp_mgr,
            self.icon_path, self.path_absolute, self.tr
        )

        # Kriging controller
        self.kriging_ctrl = KrigingController(
            kriging_view, self.data_ctrl, self.variogram_ctrl,
            self.interp_mgr, self.icon_path, self.path_absolute, self.tr
        )
        # Boundary state lives on grid_ctrl (data_ctrl exposes it via delegating
        # properties); give the kriging controller a direct grid_ctrl reference too.
        self.kriging_ctrl.grid_ctrl = self.grid_ctrl

        # The interpolation widgets are split across the variogram and kriging tabs but
        # the controllers need to read each other's tab (e.g. plot_variogram enables the
        # kriging widgets; kriging reads the fitted model/nugget/range/sill from the
        # variogram tab). Give each controller a reference to the other view so each
        # widget keeps a single owner (no duplicated state).
        self.variogram_ctrl.kriging_view = kriging_view
        self.kriging_ctrl.variogram_view = variogram_view

        # SVM controller
        self.svm_ctrl = SVMController(
            svm_view, self.data_ctrl, self.interp_mgr, self.spatial_mgr,
            self.icon_path, self.path_absolute, self.tr
        )

        # Zones controller
        self.zones_ctrl = ZonesController(
            zones_view, self.data_ctrl, self.zones_mgr,
            self.icon_path, self.path_absolute, self.tr
        )

        # data_ctrl writes target labels / variogram-enable toggles that live on
        # other tabs. Give it the owning views + variogram controller so the import
        # flow routes those writes correctly (single owner per widget/flag).
        self.data_ctrl.variogram_ctrl = self.variogram_ctrl
        self.data_ctrl.variogram_view = variogram_view
        self.data_ctrl.kriging_view = kriging_view
        self.data_ctrl.svm_view = svm_view

        # UI controller (about dialog). Language is auto-detected from the QGIS
        # locale at startup; there is no manual language switch.
        self.ui_ctrl = UIController(self.dlg, self.plugin_dir, self.icon_path, self.tr)
        self.dlg.label_About.mousePressEvent = self.ui_ctrl.on_about_clicked

        # Wire data view signals
        data_view.import_clicked.connect(self.data_ctrl.on_import_qgis_clicked)
        data_view.layer_changed.connect(self.data_ctrl.on_layer_combo_changed)
        data_view.pushButton_File_Save.clicked.connect(self.data_ctrl.on_file_save_clicked)
        data_view.checkBox_Eliminate_Outilier.clicked.connect(lambda: None)

        data_view.SpinBox_Pixel_Size_X.valueChanged.connect(self.grid_ctrl.on_pixel_size_x_changed)
        data_view.SpinBox_Pixel_Size_Y.valueChanged.connect(self.grid_ctrl.on_pixel_size_y_changed)
        data_view.lineEdit_XMin.editingFinished.connect(self.grid_ctrl.on_x_min_edited)
        data_view.lineEdit_XMax.editingFinished.connect(self.grid_ctrl.on_x_max_edited)
        data_view.lineEdit_YMin.editingFinished.connect(self.grid_ctrl.on_y_min_edited)
        data_view.lineEdit_YMax.editingFinished.connect(self.grid_ctrl.on_y_max_edited)
        data_view.checkBox_Area_Contorno.toggled.connect(self.grid_ctrl.on_area_contour_toggled)
        data_view.mMapLayerComboBox_AreaCont.currentIndexChanged.connect(
            self.grid_ctrl.on_contour_layer_combo_changed
        )
        data_view.pushButton_Area_Contorno.clicked.connect(self.grid_ctrl.on_contour_apply_clicked)

        # Wire variogram view signals
        variogram_view.comboBox_Modelo.currentIndexChanged.connect(
            self.variogram_ctrl.on_model_combo_changed
        )
        variogram_view.pushButton_VariogramaAjust.clicked.connect(
            self.variogram_ctrl.on_variogram_adjust_clicked
        )
        variogram_view.pushButton_VariogramaReset.clicked.connect(
            self.variogram_ctrl.on_variogram_reset_clicked
        )
        variogram_view.pushButton_VariogramaSave.clicked.connect(
            self.variogram_ctrl.on_variogram_save_clicked
        )

        # Wire kriging view signals
        kriging_view.pushButton_Krigagem.clicked.connect(
            self.kriging_ctrl.on_kriging_clicked
        )
        kriging_view.pushButton_Validacao_Cruzada_OK.clicked.connect(
            self.kriging_ctrl.on_cross_validation_clicked
        )
        kriging_view.pushButton_Krigagem_All_Variables.clicked.connect(
            self.kriging_ctrl.on_kriging_all_variables_clicked
        )
        kriging_view.checkBox_Krigagem_Alcance.toggled.connect(
            self.variogram_ctrl.on_use_range_for_search_toggled
        )
        kriging_view.lineEdit_OK_VBNumMax.editingFinished.connect(
            self.variogram_ctrl.on_vb_num_max_edited
        )
        kriging_view.lineEdit_OK_VBRaio.editingFinished.connect(
            self.variogram_ctrl.on_vb_raio_edited
        )

        # Semivariogram list (lives on the variogram tab) drives batch kriging selection.
        variogram_view.datatable_semivariogramas.itemClicked.connect(
            self.kriging_ctrl.on_semivariogram_checkbox_clicked
        )
        variogram_view.datatable_semivariogramas.doubleClicked.connect(
            self.variogram_ctrl.on_semivariogram_table_double_clicked
        )

        # Variogram tuning edit handlers
        variogram_view.lineEdit_OK_DMax.editingFinished.connect(
            self.variogram_ctrl.on_dmax_edited
        )
        variogram_view.lineEdit_OK_lags_dist.editingFinished.connect(
            self.variogram_ctrl.on_lags_distance_edited
        )
        variogram_view.lineEdit_Nugget.editingFinished.connect(
            self.variogram_ctrl.on_nugget_edited
        )
        variogram_view.lineEdit_Sill.editingFinished.connect(
            self.variogram_ctrl.on_sill_edited
        )
        variogram_view.lineEdit_Range.editingFinished.connect(
            self.variogram_ctrl.on_range_edited
        )
        variogram_view.horizontalSlider_Nugget.valueChanged.connect(
            self.variogram_ctrl.on_nugget_slider_changed
        )
        variogram_view.horizontalSlider_Sill.valueChanged.connect(
            self.variogram_ctrl.on_sill_slider_changed
        )
        variogram_view.horizontalSlider_Range.valueChanged.connect(
            self.variogram_ctrl.on_range_slider_changed
        )

        # Wire SVM view signals
        svm_view.pushButton_SVM_Add_Feature.clicked.connect(
            self.svm_ctrl.on_add_feature_clicked
        )
        svm_view.pushButton_SVM_Remove_Feature.clicked.connect(
            self.svm_ctrl.on_remove_feature_clicked
        )
        svm_view.checkBox_RFE.toggled.connect(
            self.svm_ctrl.on_rfe_toggled
        )
        svm_view.checkBox_Moran.toggled.connect(
            self.svm_ctrl.on_moran_toggled
        )
        svm_view.pushButton_SVM.clicked.connect(
            self.svm_ctrl.on_svm_clicked
        )
        svm_view.pushButton_Validacao_Cruzada_SVM.clicked.connect(
            self.svm_ctrl.on_svm_cross_validation_clicked
        )
        svm_view.pushButton_SVM_Add_Selected_Features.clicked.connect(
            self.svm_ctrl.on_add_selected_features_clicked
        )
        svm_view.comboBox_SVM_Fonte.currentIndexChanged.connect(
            self.svm_ctrl.on_source_layer_combo_changed
        )
        svm_view.mMapLayerComboBox_DenseLayer.currentIndexChanged.connect(
            self.svm_ctrl.on_dense_layer_combo_changed
        )
        svm_view.datatable_moran.itemClicked.connect(
            self.svm_ctrl.on_moran_checkbox_clicked
        )
        svm_view.lineEdit_SVM_VBNumMax.setValidator(QtGui.QIntValidator())
        svm_view.lineEdit_SVM_VBNumMax.editingFinished.connect(
            self.svm_ctrl.on_vb_num_max_edited
        )
        svm_view.lineEdit_SVM_VBRaio.setValidator(
            QtGui.QDoubleValidator(notation=QtGui.QDoubleValidator.StandardNotation)
        )
        svm_view.lineEdit_SVM_VBRaio.editingFinished.connect(
            self.svm_ctrl.on_vb_raio_edited
        )
        svm_view.datatable_SVM_Trainfeatures.doubleClicked.connect(
            self.svm_ctrl.on_train_features_table_double_clicked
        )
        svm_view.datatable_pontos_interpolados_SVM.doubleClicked.connect(
            self.svm_ctrl.on_interpolated_svm_points_table_double_clicked
        )
        svm_view.datatable_validacao_cruzada_SVM.doubleClicked.connect(
            self.svm_ctrl.on_svm_cross_validation_table_double_clicked
        )
        svm_view.label_SVM.mousePressEvent = self.svm_ctrl.on_svm_label_clicked
        svm_view.label_validacao_cruzada_SVM.mousePressEvent = (
            self.svm_ctrl.on_svm_cross_validation_label_clicked
        )

        # Filter the dense-layer combo to point/raster layers (matches old behaviour).
        svm_view.mMapLayerComboBox_DenseLayer.setFilters(
            QgsMapLayerProxyModel.PointLayer | QgsMapLayerProxyModel.RasterLayer
        )

        # Seed the SVM model (coordinates + labels + feature combo) after each data
        # import. Connected after data_ctrl.on_import_qgis_clicked so the dataframe,
        # min/max distances and v_target are populated first.
        data_view.import_clicked.connect(self._svm_post_import)

        # Wire zones view signals
        zones_view.pushButton_ZM_Add_Var.clicked.connect(
            self.zones_ctrl.on_add_var_clicked
        )
        zones_view.pushButton_ZM_Add_All_Vars_Selected.clicked.connect(
            self.zones_ctrl.on_add_all_selected_vars_clicked
        )
        zones_view.pushButton_ZM_Remove_Var.clicked.connect(
            self.zones_ctrl.on_remove_var_clicked
        )
        zones_view.pushButton_ZM_Calc_Nr_Ideal_ZM.clicked.connect(
            self.zones_ctrl.on_calc_ideal_zones_clicked
        )
        zones_view.spinBox_ZM_NrZonas.valueChanged.connect(
            self.zones_ctrl.on_zone_count_changed
        )
        zones_view.pushButton_ZM_Calcular.clicked.connect(
            self.zones_ctrl.on_calculate_zones_clicked
        )
        zones_view.datatable_ZM_Maps.itemClicked.connect(
            self.zones_ctrl.on_zone_maps_checkbox_clicked
        )
        zones_view.datatable_ZM.doubleClicked.connect(
            self.zones_ctrl.on_zone_vars_table_double_clicked
        )
        zones_view.datatable_ZM_Classe.doubleClicked.connect(
            self.zones_ctrl.on_zone_results_table_double_clicked
        )
        zones_view.label_ZM_FPI_NCE.mousePressEvent = \
            self.zones_ctrl.on_fpi_nce_label_clicked
        zones_view.label_ZM.mousePressEvent = \
            self.zones_ctrl.on_zones_label_clicked

    def _svm_post_import(self):
        """Seed SVM state after a data import.

        Establishes df_SVM_Trainfeatures (X, Y) / df_SVM_Trainlabels (v_target),
        SVM-search bounds and line-edit defaults, then populates the SVM feature
        combo from the attribute-table source (index 0). Runs after the data
        controller's import handler so all data_ctrl state is ready.
        """
        if self.data_ctrl.df is None:
            return
        try:
            self.svm_ctrl.seed_train_state()
            svm_view = self.dlg.get_svm_view()
            svm_view.label_VTargetSVM.setText(self.tr('Z') + ': ' + str(self.data_ctrl.v_target))
            # Drive the source combo (attribute table) to populate the feature list.
            svm_view.comboBox_SVM_Fonte.setCurrentIndex(0)
            self.svm_ctrl.on_source_layer_combo_changed(0)
        except Exception:
            # SVM seeding is best-effort; never block the data import workflow.
            pass

    def run(self):
        """Run method that performs all the real work"""

        #check if plugin is running 
        isrunning = plugins["Smart_Map"]
        if (isrunning.dlg):
          if isrunning.dlg.isVisible():
             isrunning.dlg.activateWindow()
             return
 

        self.path_absolute = QgsProject.instance().readPath("./")

        # No saved QGIS project -> fall back to the user's home directory so the
        # plugin can still run (generated files go to <home>/Smart-Map).
        if self.path_absolute == './':
            self.path_absolute = os.path.expanduser('~')


        # --- Resolve the working directory (project dir / Smart-Map) -------
        # Controllers are constructed with this path, so it must be final
        # BEFORE _initialize_controllers runs.
        project_dir = self.path_absolute
        if not os.path.isdir(os.path.join(project_dir, 'Smart-Map')):
            os.mkdir(os.path.join(project_dir, 'Smart-Map'))
        self.path_absolute = os.path.join(project_dir, 'Smart-Map')

        # Language is auto-detected and the translator installed in __init__.

        # --- Build a fresh dialog + controllers every run ------------------
        self.dlg = SmartMapDialog(self.iface, self.plugin_dir, self.icon_path, self.tr)
        self.first_start = False

        # Controllers self-wire their view signals in _initialize_controllers.
        self._initialize_controllers()

        # --- Execution counter ---------------------------------------------
        exec_path = os.path.join(self.plugin_dir, 'utils', 'execute_number.txt')
        if os.path.isfile(exec_path):
            with open(exec_path, 'r') as f:
                exec_number = int(f.read()) + 1
        else:
            exec_number = 1
        with open(exec_path, 'w') as f:
            f.write(str(exec_number))

        # --- Window setup --------------------------------------------------
        self.dlg.closeEvent = self.closeEvent
        self.dlg.setWindowFlag(QtCore.Qt.WindowMinimizeButtonHint, True)
        self.dlg.setWindowIcon(QtGui.QIcon(self.icon_path))

        # Show the working directory in the data tab.
        self.dlg.get_data_view().lineEdit.setText(self.path_absolute)

        # --- Show + initial population -------------------------------------
        self.dlg.show()

        # Trigger the attribute-table layer handler if a layer is preselected.
        data_view = self.dlg.get_data_view()
        if data_view.mMapLayerComboBox.currentIndex() >= 0:
            self.data_ctrl.on_layer_combo_changed(
                data_view.mMapLayerComboBox.currentIndex()
            )

        # Populate the management-zones map list from any existing results.
        self.zones_ctrl.load_maps_to_generate_zones()

        result = self.dlg.exec_()

        if result:
            pass

